# Generated by Django 4.1.5 on 2023-01-24 16:51

import dbjob.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('graph', models.FileField(blank=True, upload_to=dbjob.models.user_directory_path, verbose_name='График')),
            ],
        ),
    ]
